

# This file was *autogenerated* from the file circuits/voting/multi/multi_vote_voting.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
from proving_pipeline.circuit_wrapper.circuit import Circuit
import random

class Multi_vote_voting(Circuit):
    def __init__(self, params):
        super().__init__(params)

    def generate_random_ballot(self, n_votes, max_votes_per_candidate, max_votes_total):
        rest_votes = max_votes_total
        votes = []
        for i in range(n_votes):
            vote = random.randint(_sage_const_0 , min(max_votes_per_candidate, rest_votes))
            votes.append(vote)
            rest_votes -= vote
        self.votes = votes
        return votes
    
    def generate_input(self, existing_input, constants):
        input = {}
        n_votes = int(self.retrieve_global_data("constants", "n_votes", constants))
        max_votes_per_candidate = int(self.retrieve_global_data("constants", "max_votes_cand", constants))
        max_votes_total = int(self.retrieve_global_data("constants", "max_choices", constants))
        ballot = self.generate_random_ballot(n_votes, max_votes_per_candidate, max_votes_total)
        input["ballot"] = ballot

        self.input = input
        return input

    def serialize(self):
        state = super().serialize()
        if self.votes:
            state["params"]["votes"] = self.votes
        return state

    def deserialize(self, state):
        super().deserialize(state)
        if state["params"].get("votes"):
            self.votes = [int(vote) for vote in state["params"]["votes"]]

